<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('pages')->delete();

        DB::table('pages')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'url' => '/',
                    'title' => '{"hy":"Գլխավոր","ru":"Главное","en":"Home"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 0,
                    'about' => 0,
                    'buyers' => 0,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'home',
                    'active' => 1,
                    'ordering' => 1,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 14:30:59',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            1 =>
                array (
                    'id' => 2,
                    'url' => 'about-us',
                    'title' => '{"hy":"Մեր մասին","ru":"О нас","en":"About Us"}',
                    'image' => NULL,
                    'show_image' => 0,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 1,
                    'buyers' => 0,
                    'content' => '{"ru":null}',
                    'title_content' => '{"ru":null}',
                    'static' => 'about-us',
                    'active' => 1,
                    'ordering' => 7,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 14:34:04',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            2 =>
                array (
                    'id' => 3,
                    'url' => 'vacancies',
                    'title' => '{"hy":"Թափուր աշխատատեղեր","ru":"Свободные места","en":"Vacancies"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 1,
                    'buyers' => 0,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'vacancies',
                    'active' => 1,
                    'ordering' => 2,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 14:42:13',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            3 =>
                array (
                    'id' => 4,
                    'url' => 'contacts',
                    'title' => '{"hy":"Կոնտակտներ","ru":"Контакты","en":"Contacts"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 1,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 1,
                    'buyers' => 0,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'contacts',
                    'active' => 1,
                    'ordering' => 3,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            4 =>
                array (
                    'id' => 5,
                    'url' => 'blogs',
                    'title' => '{"hy":"Բլոգ","ru":"Блог","en":"Blog"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 1,
                    'buyers' => 0,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'blogs',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            5 =>
                array (
                    'id' => 6,
                    'url' => 'how-to-payment',
                    'title' => '{"hy":"Վճարում","ru":"Оплата","en":"Payment"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'how-to-payment',
                    'active' => 1,
                    'ordering' => 5,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 14:52:44',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            6 =>
                array (
                    'id' => 7,
                    'url' => 'promotions-and-competitions',
                    'title' => '{"hy":"Առաջխաղացումներ և մրցույթներ","ru":"Акции и конкурсы","en":"Promotions and competitions"}',
                    'image' => NULL,
                    'show_image' => 0,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"ru":null}',
                    'title_content' => '{"ru":null}',
                    'static' => 'promotions-and-competitions',
                    'active' => 1,
                    'ordering' => 12,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 14:54:22',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            7 =>
                array (
                    'id' => 8,
                    'url' => 'collection',
                    'title' => '{"hy":"Հավաքածուներ","ru":"Правила продажи","en":"Sales rules"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 1,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'collection',
                    'active' => 1,
                    'ordering' => 8,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:00:03',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            8 =>
                array (
                    'id' => 9,
                    'url' => 'discounts',
                    'title' => '{"hy":"Զեղչեր","ru":"Заказ","en":"Discounts"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'how-to-order',
                    'active' => 1,
                    'ordering' => 6,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:03:08',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            9 =>
                array (
                    'id' => 10,
                    'url' => 'shipment',
                    'title' => '{"hy":"Առաքում և վճարում","ru":"Отгрузка","en":"Shipment"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 1,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'shipment',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),
            10 =>
                array (
                    'id' => 11,
                    'url' => 'how-to-return',
                    'title' => '{"hy":"Վերադարձ","ru":"Возвращаться","en":"Return"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'how-to-return',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

            11 =>
                array (
                    'id' => 12,
                    'url' => 'store-addresses',
                    'title' => '{"hy":"Խանութներ","ru":"Адреса магазинов","en":"Store addresses"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 1,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'shops',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

            12 =>
                array (
                    'id' => 13,
                    'url' => 'privacy-policy',
                    'title' => '{"hy":"Գաղտնիության քաղաքականություն","ru":"Политика конфиденциальности","en":"Privacy Policy"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'privacy-policy',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

            13 =>
                array (
                    'id' => 14,
                    'url' => 'product-care-rules',
                    'title' => '{"hy":"Արտադրանքի խնամքի կանոններ","ru":"Правила ухода за изделием","en":"Product care rules"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'product-care-rules',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

            14 =>
                array (
                    'id' => 15,
                    'url' => 'size-chart',
                    'title' => '{"hy":"Կուտակային համակարգ","ru":"Таблица размеров","en":"Size chart"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 1,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'size-chart',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

            15 =>
                array (
                    'id' => 16,
                    'url' => 'frequently-asked-questions',
                    'title' => '{"hy":"Հաճախակի տրվող հարցեր","ru":"Часто задаваемые вопросы","en":"Frequently Asked Questions"}',
                    'image' => NULL,
                    'show_image' => 1,
                    'to_top' => 0,
                    'to_menu' => 0,
                    'to_footer' => 1,
                    'about' => 0,
                    'buyers' => 1,
                    'content' => '{"en":null}',
                    'title_content' => '{"en":null}',
                    'static' => 'frequently-asked-questions',
                    'active' => 1,
                    'ordering' => 9,
                    'seo_title' => '{"en":null}',
                    'seo_description' => '{"en":null}',
                    'seo_keywords' => '{"ru":null}',
                    'created_at' => '2020-11-18 15:12:28',
                    'updated_at' => '2020-11-18 15:49:37',
                ),

        ));

    }
}
